Not reload same file multiple times
TalwalkarLab/leaf pull request #44
Opened 2021-10-26 18:37 UTC by JohnlNguyen

For sen140, there is 1 json file and 600k+ users. In split_data.py, it is loading from file the same json file 600k+ times. This is highly inefficient. 

```
[ ... ('uncoveredrivers', 1, 'all_data_niid_0_keep_1.json'), ('OHHkim', 1, 'all_data_niid_0_keep_1.json'), ('ohhcamille', 1, 'all_data_niid_0_keep_1.json'), ('amarkrdubedy', 2, 'all_data_niid_0_keep_1.json'), ('Yalovyy', 3, 'all_data_niid_0_keep_1.json'), ('kmjohnson14', 1, 'all_data_niid_0_keep_1.json'), ('WalletMusic', 1, 'all_data_niid_0_keep_1.json'), ('devinhamilton', 1, 'all_data_niid_0_keep_1.json'), ('AndiFashion', 1, 'all_data_niid_0_keep_1.json'), ('sgtcrid', 6, 'all_data_niid_0_keep_1.json'), ('conorravo', 1, 'all_data_niid_0_keep_1.json'), ('ankit4u', 2, 'all_data_niid_0_keep_1.json'), ('JessicaJeane', 2, 'all_data_niid_0_keep_1.json'), ('Dev92', 1, 'all_data_niid_0_keep_1.json'), ('rhebzie', 1, 'all_data_niid_0_keep_1.json')
```

This PR checks if the previous file is the same as the new file. If it is the same, then don't load the same file again.

2021-11-02 20:37 UTC, JohnlNguyen commented
@scaldas would you mind taking a look?

2021-11-20 14:19 UTC, scaldas requested changes
Minor fix and I'll merge.

2021-11-20 14:19 UTC, scaldas commented on data/utils/split_data.py
> -    if include_hierarchy:
Getting rid of these conditional makes it so hierarchies is no longer initialized anywhere. This probably didn't break anything, as I believe we don't use hierarchies yet.

2021-12-07 23:34 UTC, JohnlNguyen commented
addressed comment

2021-12-08 21:40 UTC, merged